### ISSUE TITLE
Integrate CIrcle-CI 2.0 to the project

### ISSUE THREAD

**Issue by jogendra** [jogendra/LoadingShimmer#18]
**Actual Behaviour**

Currently, no any hook for checking PR quality and testing.

**Expected Behaviour**

Integrate Circle-CI

**Steps to reproduce it**

**Screenshots of the issue**

N/A

**Would you like to work on the issue?**

Yes

**Comment by w7788129** [comment]
看不懂

**Comment by Ethenyl** [comment]
Hi @jogendra,

I'll gladly work on it, any particular reason for **CircleCI** ? Would **TravisCI** do the job too ?

After choosing the CI, I should be able to add a coverage report with CodeCov.
