### ISSUE TITLE
Cannot open example project

### ISSUE THREAD

**Issue by HoangHuyPhi** [jogendra/LoadingShimmer#22]
**Actual Behaviour**

I try to open example project but it shows me errors "Multiple commands produce...". I use Xcode 10.1

**Expected Behaviour**

The example app should open

**Steps to reproduce it**
Follow the guideline README in the project. 
**Screenshots of the issue**

<img width="1280" alt="screen shot 2019-02-27 at 16 40 53" src="https://user-images.githubusercontent.com/32318345/53468646-31297880-3aaf-11e9-8b8b-203c50d56f10.png">

**Would you like to work on the issue?**
yes

**Comment by jogendra** [comment]
Hi @HoangHuyPhi I think the issue is not with an example project, just clean the project with `Command + Shift + K` and try rebuilding, it may work. In case you have a solution of this please feel free to open a PR. Thanks :)
