### ISSUE TITLE
When using Pod, not able to access access class due to internal access

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [jogendra/LoadingShimmer#25]
I integrated using Pod, but couldn't able to access `LoadingShimmer` class due to default `internal` access of class.

I made public access to that class by putting `public` keyword.

```
public class LoadingShimmer: NSObject {
    public static let shared = LoadingShimmer()

    public class func startCovering(_ view: UIView?) {
        shared.coverSubviews(view)
    }

    public class func stopCovering(_ view: UIView?) {
        shared.removeSubviews(view)
    }

}
```

Would you please do the same changes in repo.

Thanks.

**Comment by jogendra** [comment]
Thank you @Rashesh-Bosamiya for opening the issue. I will make it public class, it was a silly mistake.

**Comment by jogendra** [comment]
Fixed in https://github.com/jogendra/LoadingShimmer/commit/f04bfef6e7353b8352ae8d31d571d5519ffd403b
