### ISSUE TITLE
Using Loading Shimmer changes view background color

### ISSUE THREAD

**Issue by vmammanalupo** [jogendra/LoadingShimmer#27]
**Actual Behaviour**
Using Loading Shimmer changes a view's background color (always white background).

**Expected Behaviour**
Using Loading Shimmer honors the target view's background color, via using it as the backdrop while blurring its contained elements.

**Steps to reproduce it**
1. Have a view with a background color.
2. Cover that view with a loading shimmer via LoadingShimmer.startCovering(view)
3. Hide the loading shimmer via LoadingShimmer.stopCovering(view)

Observe that the original background color is not honored.

**Comment by jogendra** [comment]
@vmammanalupo thank you for an opening issue. Can you please work on it? or I will look into it as soon as possible.
