### ISSUE TITLE
Loader for TableView Cells is hardcoded in Library

### ISSUE THREAD

**Issue by hemant3370** [jogendra/LoadingShimmer#30]
`let coverableCellsIds = ["Cell1", "Cell1", "Cell1", "Cell1", "Cell1"]
        if type(of: view!) === UITableView.self {
            for i in 0..<coverableCellsIds.count {
                getTableViewPath(view, index: i, coverableCellsIds: coverableCellsIds)
            }
            addCover(view)
            return
        }`

**Comment by jogendra** [comment]
Hi @hemant3370 I am adding `coverableCellsIds` to the initializer in next release. If you have any other best thing on mind, please suggest. thanks :)
